# Generated by Django 6.0.5 on 2026-05-29 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in NGN', max_digits=10)),
                ('available_sizes', models.CharField(default='S, M, L, XL, XXL', help_text='Comma-separated sizes, e.g. S, M, L, XL', max_length=200)),
                ('available_colors', models.CharField(default='Black', help_text='Comma-separated colors, e.g. Black, Navy, Beige', max_length=200)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('is_available', models.BooleanField(default=True, help_text='Hide if sold out')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload product photo', upload_to='products/')),
                ('is_primary', models.BooleanField(default=False, help_text='Main image shown in listings')),
                ('alt_text', models.CharField(blank=True, help_text='Describe the image for accessibility', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
            options={
                'ordering': ['-is_primary', 'order'],
            },
        ),
    ]
