# Generated by Django 6.0.5 on 2026-05-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='color',
            field=models.CharField(blank=True, help_text='Color name this image represents (e.g. "Midnight Black"). Leave blank if not color-specific.', max_length=100),
        ),
    ]
